variables:
  service_name: mock-nhsid-jwks
  short_service_name: mock-nhsid-jwks
  service_base_path: mock-nhsid-jwks
  product_display_name: Mock NHSID JWKS Endpoint
  product_description: Mock NHSID JWKS Endpoint
