variables:
  service_name: mock-nhsid-jwks-endpoint
  short_service_name: mock-nhsid-jwks-endpoint
  service_base_path: mock-nhsid-jwks-endpoint
  product_display_name: Mock NHSID JWKS Endpoint
  product_description: Mock NHSID JWKS Endpoint
