# This is an OpenAPI Specification (https://swagger.io/specification/)
# for {{ SERVICE_NAME }} owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: '{{ SERVICE_NAME }}'
  version: d5a3f4fc-e61f-41f3-ab72-16aa5ef3ff3c
  description: |
    ## Overview
    Add a fully fledged description here with markdown syntax.
    For help completing the content of your API spec, see our guidance on the minimum standard (bronze) details 
    to include [here](https://nhsd-confluence.digital.nhs.uk/display/APM/Writing+a+bronze+API+cover+page). You should also base your content on our exemplar API - [PDS FHIR](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir).
    ## Who can use this API
    To be completed.
    ## Related APIs
    To be completed.
    ## API status and roadmap
    To be completed.
    ## Service level
    To be completed.
    ## Technology
    To be completed.
    ## Network access
    To be completed.
    ## Security and authorisation
    To be completed.
    ## Environments and testing
    To be completed.
    ## Onboarding
    To be completed.
  contact:
    name: '{{ SERVICE_NAME }} API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/{{ SERVICE_BASE_PATH }}'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/{{ SERVICE_BASE_PATH }}'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/{{ SERVICE_BASE_PATH }}'
    description: Production environment.
paths: { }
